"""updates

Revision ID: 5f31e6cfcb62
Revises: 486edab0b800
Create Date: 2024-08-09 16:58:24.372796+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f31e6cfcb62'
down_revision = '486edab0b800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('core_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['core_id'], ['core.id'], name=op.f('fk_flags_core_id_core')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_flags_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('core_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['core_id'], ['core.id'], name=op.f('fk_saves_core_id_core')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saves_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saves')
    op.drop_table('flags')
    # ### end Alembic commands ###
