"""more updates

Revision ID: c9025bae20fd
Revises: 5f31e6cfcb62
Create Date: 2024-08-10 04:08:41.590629+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9025bae20fd'
down_revision = '5f31e6cfcb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('image_url')
        batch_op.drop_column('link_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###
