"""Image resource

Revision ID: 486edab0b800
Revises: b10d60da56cb
Create Date: 2024-08-06 09:44:53.764710+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486edab0b800'
down_revision = 'b10d60da56cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_features', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core', schema=None) as batch_op:
        batch_op.drop_column('image_features')

    # ### end Alembic commands ###
